hmrc/penalties-appeals-frontend

- app/controllers/ReasonableExcuseController.scala
- app/forms/ReasonableExcuseForm.scala
- app/helpers/FormProviderHelper.scala
- app/models/ReasonableExcuse.scala
- app/utils/SessionKeys.scala
- app/views/AppealStartPage.scala.html
- app/views/ErrorTemplate.scala.html
- app/views/ReasonableExcuseSelectionPage.scala.html
- app/views/components/radios.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/connectors/PenaltiesConnectorISpec.scala
- it/controllers/ReasonableExcuseControllerISpec.scala
- it/stubs/PenaltiesStub.scala
- it/utils/IntegrationSpecCommonBase.scala
- test/assets/messages/ReasonableExcuseSelectionMessages.scala
- test/controllers/ReasonableExcuseControllerSpec.scala
- test/forms/FormBehaviours.scala
- test/forms/ReasonableExcuseFormSpec.scala
- test/helpers/FormProviderHelperSpec.scala
- test/models/ReasonableExcuseSpec.scala
- test/views/ReasonableExcuseSelectionPageSpec.scala
https://user-images.githubusercontent.com/53828896/118256362-4d097100-b4a5-11eb-8289-e72f4dd23238.mov
> [PRM-223] - Reasonable excuse selection page

- app/assets/javascripts/backLink.js
- app/controllers/CheckYourAnswersController.scala
- app/controllers/CrimeReasonController.scala
- app/helpers/SessionAnswersHelper.scala
- app/views/CheckYourAnswersPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/CheckYourAnswersControllerISpec.scala
- it/controllers/CrimeReasonControllerISpec.scala
- test/assets/messages/CheckYourAnswersMessages.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/CrimeReasonControllerSpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
- test/views/CheckYourAnswersPageSpec.scala
Focuses on crime reasonable excuse journey, also fixed the back button issue with form resubmission
> [PRM-262] - Check your answers page template

- app/controllers/MakingALateAppealController.scala
- app/forms/MakingALateAppealForm.scala
- app/helpers/FormProviderHelper.scala
- app/utils/SessionKeys.scala
- app/views/MakingALateAppealPage.scala.html
- app/views/components/textArea.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/MakingALateAppealControllerISpec.scala
- test/assets/messages/MakingALateAppealMessages.scala
- test/controllers/MakingALateAppealControllerSpec.scala
- test/helpers/FormProviderHelperSpec.scala
- test/views/MakingALateAppealPageSpec.scala
https://user-images.githubusercontent.com/53828896/121328468-420ef880-c90c-11eb-9be7-754e2c04e2ae.mov
> [PRM-284] - Added making a late appeal page and routing to CYA from page

- app/helpers/SessionAnswersHelper.scala
- app/utils/SessionKeys.scala
- conf/messages
- conf/messages.cy
- it/controllers/CheckYourAnswersControllerISpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
- test/navigation/NavigationSpec.scala
> [PRM-285] - Why you did not appeal sooner text on CYA page

- app/controllers/HonestyDeclarationController.scala
- app/helpers/HonestyDeclarationHelper.scala
- app/views/HonestyDeclarationPage.scala.html
- conf/messages
- it/controllers/HonestyDeclarationControllerISpec.scala
- test/assets/messages/HonestyDeclarationMessages.scala
- test/helpers/HonestyDeclarationHelperSpec.scala
- test/views/HonestyDeclarationPageSpec.scala
> [PRM-296] - Added extra bullet on honesty declaration page

- app/controllers/HonestyDeclarationController.scala
- app/controllers/LossOfStaffReasonController.scala
- app/forms/WhenDidPersonLeaveTheBusinessForm.scala
- app/navigation/Navigation.scala
- app/utils/ReasonableExcuses.scala
- app/utils/SessionKeys.scala
- app/views/components/inputDate.scala.html
- app/views/reasonableExcuseJourneys/lossOfStaff/WhenDidThePersonLeaveBusinessPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/CrimeReasonControllerISpec.scala
- it/controllers/LossOfStaffReasonControllerISpec.scala
- test/assets/messages/WhenDidThePersonLeaveBusinessMessages.scala
- test/controllers/CrimeReasonControllerSpec.scala
- test/controllers/FireOrFloodReasonControllerSpec.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/controllers/LossOfStaffReasonControllerSpec.scala
- test/forms/WhenDidPersonLeaveTheBusinessFormSpec.scala
- test/navigation/NavigationSpec.scala
- test/views/HonestyDeclarationPageSpec.scala
- test/views/WhenDidThePersonLeaveBusinessPageSpec.scala
> [PRM-297] - Loss of staff page + navigation + tests

- app/helpers/SessionAnswersHelper.scala
- app/models/appeals/AppealSubmission.scala
- conf/messages
- conf/messages.cy
- it/controllers/CheckYourAnswersControllerISpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
- test/models/appeals/AppealSubmissionSpec.scala
> [PRM-291]:  Updated CYA page and created new payload for fire or flood

- app/models/appeals/AppealSubmission.scala
- it/controllers/CheckYourAnswersControllerISpec.scala
- it/services/AppealServiceISpec.scala
- test/models/appeals/AppealSubmissionSpec.scala
> [PRM-300] - Added payload model on appeal submission for loss of staff

- app/controllers/HonestyDeclarationController.scala
- app/controllers/TechnicalIssuesReasonController.scala
- app/forms/WhenDidTechnologyIssuesBeginForm.scala
- app/forms/WhenDidTechnologyIssuesEndForm.scala
- app/forms/mappings/LocalDateFormatter.scala
- app/forms/mappings/Mappings.scala
- app/navigation/Navigation.scala
- app/utils/ReasonableExcuses.scala
- app/utils/SessionKeys.scala
- app/views/reasonableExcuseJourneys/technicalIssues/TechnologyIssuesDatePage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/TechnicalIssuesReasonControllerISpec.scala
- test/assets/messages/WhenDidTechnologyIssuesBeginMessages.scala
- test/assets/messages/WhenDidTechnologyIssuesEndMessages.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/controllers/TechnicalIssuesReasonControllerSpec.scala
- test/forms/WhenDidTechnologyIssuesBeginFormSpec.scala
- test/forms/WhenDidTechnologyIssuesEndFormSpec.scala
- test/navigation/NavigationSpec.scala
- test/views/TechnologyIssuesDatePageSpec.scala
- test/views/WhenDidThePersonLeaveBusinessPageSpec.scala
Need to check if the error messages are correct.
> [PRM-303] - Added technical issues begin and end page pt.1

- it/controllers/TechnicalIssuesReasonControllerISpec.scala
> [PRM-303] - Added technical issues begin and end page pt.2

- app/helpers/SessionAnswersHelper.scala
- conf/messages
- conf/messages.cy
- it/controllers/CheckYourAnswersControllerISpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
> [PRM-306] - Added CYA page variation for technical issues page

- app/controllers/HealthReasonController.scala
- app/controllers/HonestyDeclarationController.scala
- app/forms/WasHospitalStayRequiredForm.scala
- app/forms/WhenDidHealthIssueHappenForm.scala
- app/utils/ReasonableExcuses.scala
- app/utils/SessionKeys.scala
- app/views/components/radios.scala.html
- app/views/reasonableExcuseJourneys/health/WasHospitalStayRequiredPage.scala.html
- app/views/reasonableExcuseJourneys/health/WhenDidHealthReasonHappenPage.scala.html
- app/viewtils/RadioOptionHelper.scala
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/HealthReasonControllerISpec.scala
- test/assets/messages/WasHospitalStayRequiredMessages.scala
- test/assets/messages/WhenDidHealthReasonHappenMessages.scala
- test/controllers/HealthReasonControllerSpec.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/forms/WasHospitalStayRequiredFormSpec.scala
- test/forms/WhenDidHealthIssueHappenFormSpec.scala
- test/views/WasHospitalStayRequiredPageSpec.scala
- test/views/WhenDidHealthReasonHappenPageSpec.scala
Added Did health issue include hospital stay and when did you become unable to manage the VAT account pages
> [PRM-328] - added health appeal pages for no hospital stay

- app/views/layouts/Layout.scala.html
- conf/application.conf
> [COOKIE_CONSENT] - Added cookie consent

- app/helpers/SessionAnswersHelper.scala
- app/models/appeals/AppealSubmission.scala
- app/utils/SessionKeys.scala
- conf/messages
- conf/messages.cy
- it/controllers/CheckYourAnswersControllerISpec.scala
- it/services/AppealServiceISpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
- test/models/appeals/AppealSubmissionSpec.scala
No screenshot yet due to pages not being implemented
> [PRM-330] - Added CYA page variation for health (no hospital stay)

- app/helpers/SessionAnswersHelper.scala
- app/services/AppealService.scala
- app/utils/SessionKeys.scala
- conf/messages
- conf/messages.cy
- it/controllers/CheckYourAnswersControllerISpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
File upload w/ late appeal
File upload no late appeal
No file upload no late appeal
No file upload late appeal
> [PRM-360] - CYA page for 'Other' reason

- app/controllers/HealthReasonController.scala
- app/forms/WhenDidHospitalStayBeginForm.scala
- app/navigation/Navigation.scala
- app/views/reasonableExcuseJourneys/health/WhenDidHospitalStayBeginPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/HealthReasonControllerISpec.scala
- test/assets/messages/WhenDidHospitalStayBeginMessages.scala
- test/controllers/HealthReasonControllerSpec.scala
- test/forms/WhenDidHospitalStayBeginFormSpec.scala
- test/navigation/NavigationSpec.scala
- test/views/WhenDidHospitalStayBeginPageSpec.scala
Resolved the gitHub GPG key issue and pushed it again
> PRM-311 Added changes and test cases for When Did Hospital Stay Begin

- app/controllers/HealthReasonController.scala
- app/models/pages/Page.scala
- app/navigation/Navigation.scala
- app/viewtils/RadioOptionHelper.scala
- it/controllers/HealthReasonControllerISpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/CrimeReasonControllerSpec.scala
- test/controllers/FireOrFloodReasonControllerSpec.scala
- test/controllers/HealthReasonControllerSpec.scala
- test/models/ModeSpec.scala
- test/navigation/NavigationSpec.scala
Routing for Hospital stay beginning is covered in PRM-311
> [PRM-310] Navigation for Has Hospital Stay Ended

- app/helpers/SessionAnswersHelper.scala
- conf/messages
- conf/messages.cy
- it/controllers/CheckYourAnswersControllerISpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
> [PRM-383] - Added 'Not provided' message when user has not uploaded a file

- app/views/reasonableExcuseJourneys/other/WhyReturnSubmittedLatePage.scala.html
> [PRM-A11yFix] - Removed invalid aria-describedby

- app/controllers/AgentsController.scala
- app/forms/WhyReturnWasSubmittedLateAgentForm.scala
- app/utils/SessionKeys.scala
- app/views/agents/WhyWasTheReturnSubmittedLateAgentPage.scala.html
- app/viewtils/RadioOptionHelper.scala
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/AgentsControllerISpec.scala
- test/assets/messages/WhyWasTheReturnSubmittedLateAgentMessages.scala
- test/controllers/AgentsControllerSpec.scala
- test/forms/WhyReturnWasSubmittedLateAgentFormSpec.scala
- test/views/WhyWasTheReturnSubmittedLateAgentPageSpec.scala
- test/viewtils/RadioOptionHelperSpec.scala
> [PRM-407] - Added 'Why return was submitted late' for agent

- app/models/appeals/AppealSubmission.scala
- it/connectors/PenaltiesConnectorISpec.scala
- test/connectors/PenaltiesConnectorSpec.scala
- test/models/appeals/AppealSubmissionSpec.scala
Backend change to go a long with frontend change https://github.com/hmrc/penalties/pull/37
> [PRM-409] Added agent questions to appeal model

- app/helpers/HonestyDeclarationHelper.scala
- conf/messages
- conf/messages.cy
- test/assets/messages/HonestyDeclarationMessages.scala
- test/assets/messages/WasHospitalStayRequiredMessages.scala
- test/helpers/HonestyDeclarationHelperSpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
- test/views/HonestyDeclarationPageSpec.scala
> [PRM-443] - Updated health reason content

- app/views/AppealConfirmationPage.scala.html
- conf/messages
- conf/messages.cy
- test/assets/messages/AppealConfirmationMessages.scala
- test/views/AppealConfirmationPageSpec.scala
> [PRM-457] - Updated confirmation page for appealing against an obligation

- app/controllers/CheckYourAnswersController.scala
- app/helpers/SessionAnswersHelper.scala
- app/utils/SessionKeys.scala
- conf/messages
- conf/messages.cy
- it/controllers/CheckYourAnswersControllerISpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
> [PRM-456] - Added CYA page variation for appealing against the obligation

- app/controllers/AppealAgainstObligationController.scala
- app/controllers/CrimeReasonController.scala
- app/forms/OtherRelevantInformationForm.scala
- app/views/obligation/OtherRelevantInformationPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/AgentsControllerISpec.scala
- it/controllers/AppealAgainstObligationControllerISpec.scala
- it/controllers/AppealStartControllerISpec.scala
- it/controllers/BereavementReasonControllerISpec.scala
- it/controllers/CrimeReasonControllerISpec.scala
- it/controllers/FireOrFloodReasonControllerISpec.scala
- it/controllers/HonestyDeclarationControllerISpec.scala
- it/controllers/LossOfStaffReasonControllerISpec.scala
- it/controllers/OtherReasonControllerISpec.scala
- it/controllers/ReasonableExcuseControllerISpec.scala
- test/assets/messages/OtherRelevantInformationMessages.scala
- test/controllers/AppealAgainstObligationControllerSpec.scala
- test/controllers/OtherReasonControllerSpec.scala
- test/forms/OtherRelevantInformationFormSpec.scala
- test/views/OtherRelevantInformationPageSpec.scala
> [PRM-461] - Added 'tell us why you want to appeal the penalty' page + controller + tests

- app/controllers/OtherPenaltiesForPeriodController.scala
- app/forms/OtherPenaltiesForPeriodForm.scala
- app/views/OtherPenaltiesForPeriodPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/OtherPenaltiesForPeriodControllerISpec.scala
- test/assets/messages/OtherPenaltiesForPeriodMessages.scala
- test/controllers/OtherPenaltiesForPeriodControllerSpec.scala
- test/forms/OtherPenaltiesForPeriodFormSpec.scala
- test/views/OtherPenaltiesForPeriodPageSpec.scala
> [PRM-453]: added Other penalties for this period page

- app/helpers/SessionAnswersHelper.scala
- conf/messages
- conf/messages.cy
- test/helpers/SessionAnswersHelperSpec.scala
> [PRM-475] - Updated content on CYA page for LPP

- app/views/AppealConfirmationPage.scala.html
- test/views/AppealConfirmationPageSpec.scala
> [PRM-477]: removed email/secure message on submission page for agent appeal journey

- app/views/AppealStartPage.scala.html
> [PRM-479]: obligation landing page content fix

- app/controllers/AppealAgainstObligationController.scala
- app/controllers/CancelVATRegistrationController.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/HonestyDeclarationController.scala
- app/controllers/OtherPenaltiesForPeriodController.scala
- app/helpers/SessionAnswersHelper.scala
- app/models/pages/Page.scala
- app/navigation/Navigation.scala
- app/views/AppealStartPage.scala.html
- it/controllers/AppealAgainstObligationControllerISpec.scala
- it/controllers/CancelVATRegistrationControllerISpec.scala
- it/controllers/CheckYourAnswersControllerISpec.scala
- it/controllers/OtherPenaltiesForPeriodControllerISpec.scala
- test/controllers/AppealAgainstObligationControllerSpec.scala
- test/controllers/CancelVATRegistrationControllerSpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
- test/navigation/NavigationSpec.scala
Navigation for Appeal against Obligation cancel vat registration  with test cases
> PRM-471 Navigation for Appeal against Obligation

- app/views/ReasonableExcuseSelectionPage.scala.html
- conf/messages
- conf/messages.cy
- test/assets/messages/ReasonableExcuseSelectionMessages.scala
- test/views/ReasonableExcuseSelectionPageSpec.scala
> [PRM-494]: updated Reasonable excuse list page title for lsp's

- app/controllers/CancelVATRegistrationController.scala
- app/controllers/SignOutController.scala
- app/services/monitoring/AuditService.scala
- app/views/components/details.scala.html
- app/views/components/p.scala.html
- app/views/reasonableExcuseJourneys/other/UploadEvidencePage.scala.html
- conf/messages
- conf/messages.cy
- test/assets/messages/UploadEvidenceMessages.scala
- test/controllers/CancelVATRegistrationControllerSpec.scala
- test/views/UploadEvidencePageSpec.scala
I removed the 'Upload evidence' heading as it will not be needed in future iterations (in place of multi-evidence upload)
> [PRM-588] - Updated content on file upload page

- app/views/layouts/GovUkPageLayout.scala.html
- conf/application.conf
> [PRM-605] - Add technical issues feedback link

- app/assets/javascripts/backLink.js
- app/assets/javascripts/upload/multiFileUpload.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/upload/_multi-file-upload.scss
- app/views/components/upload/uploadItem.scala.html
- app/views/layouts/GovUkPageLayout.scala.html
- app/views/layouts/Layout.scala.html
- app/views/reasonableExcuseJourneys/other/UploadEvidencePage.scala.html
- build.sbt
- conf/messages
- conf/messages.cy
- it/controllers/OtherPenaltiesForPeriodControllerISpec.scala
- test/assets/messages/UploadEvidenceMessages.scala
- test/views/UploadEvidencePageSpec.scala
https://user-images.githubusercontent.com/53828896/133430981-5832aff7-2701-40eb-97cd-38375f2e2382.mov
> [PRM-638] - Added JS + components to file upload page

- app/config/AppConfig.scala
- app/repositories/UploadJourneyRepository.scala
- conf/application.conf
- project/AppDependencies.scala
https://github.com/hmrc/app-config-qa/pull/12887/files
https://github.com/hmrc/app-config-staging/pull/9120
https://github.com/hmrc/app-config-production/pull/12489
https://github.com/hmrc/service-manager-config/pull/3822
> [PRM-653] - Added Mongo to service

- app/views/reasonableExcuseJourneys/other/UploadEvidencePage.scala.html
- conf/messages
- conf/messages.cy
- test/assets/messages/UploadEvidenceMessages.scala
- test/connectors/UpscanInitiateConnectorSpec.scala
- test/views/UploadEvidencePageSpec.scala
> [PRM-657] - Updated content on file upload page

- app/controllers/OtherReasonController.scala
- app/controllers/UpscanController.scala
- app/controllers/predicates/DataRequiredAction.scala
- app/navigation/Navigation.scala
- app/services/upscan/UpscanService.scala
- app/utils/SessionKeys.scala
- app/views/reasonableExcuseJourneys/other/noJs/UploadTakingLongerThanExpectedPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/OtherReasonControllerISpec.scala
- it/controllers/UpscanControllerISpec.scala
- it/services/upscan/UpscanServiceISpec.scala
- test/assets/messages/UploadTakingLongerThanExpectedMessages.scala
- test/controllers/OtherReasonControllerSpec.scala
- test/controllers/UpscanControllerSpec.scala
- test/navigation/NavigationSpec.scala
- test/services/upscan/UpscanServiceSpec.scala
- test/views/UploadTakingLongerThanExpectedPageSpec.scala
https://user-images.githubusercontent.com/53828896/139703754-155427f4-42eb-414f-a5fd-3bf7ec831cf0.mov
https://user-images.githubusercontent.com/53828896/139703770-0ae5e004-3d82-4393-a38b-ad5503e3fb57.mov
> [PRM-803] - Added file is taking longer than expected to upload page

- app/views/components/upload/fileUploadDialog.scala.html
- app/views/reasonableExcuseJourneys/other/noJs/UploadAnotherDocumentPage.scala.html
- conf/messages
- conf/messages.cy
- test/assets/messages/UploadAnotherDocmuentMessages.scala
- test/views/UploadAnotherDocumentPageSpec.scala
> [PRM-809] - Changed text on file dialog for uploading another document

- app/controllers/OtherReasonController.scala
- app/forms/upscan/YouHaveUploadedFilesForm.scala
- app/helpers/UpscanMessageHelper.scala
- app/models/pages/Page.scala
- app/navigation/Navigation.scala
- app/utils/SessionKeys.scala
- app/views/components/radios.scala.html
- app/views/components/upload/YouHaveUploadedFilesPage.scala.html
- app/views/reasonableExcuseJourneys/other/noJs/UploadAnotherDocumentPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/OtherReasonControllerISpec.scala
- test/assets/messages/YouHaveUploadedFilesMessages.scala
- test/controllers/OtherReasonControllerSpec.scala
- test/forms/upscan/YouHaveUploadedFilesFormSpec.scala
- test/helpers/UpscanMessageHelperSpec.scala
- test/views/components/upload/YouHaveUploadedFilesPageSpec.scala
> PRM-796 Added Page 'You have uploaded 'x' files'

- app/config/featureSwitches/FeatureSwitch.scala
- app/config/featureSwitches/FeatureSwitching.scala
- app/controllers/OtherReasonController.scala
- app/controllers/testOnly/FeatureSwitchController.scala
- conf/prod.routes
- conf/testOnlyDoNotUseInAppConf.routes
- it/controllers/OtherReasonControllerISpec.scala
- it/controllers/testOnly/FeatureSwitchControllerISpec.scala
- it/utils/IntegrationSpecCommonBase.scala
- test/config/featureSwitches/FeatureSwitchingSpec.scala
- test/controllers/OtherReasonControllerSpec.scala
- test/controllers/testOnly/FeatureSwitchControllerSpec.scala
Set via: http://localhost:9181/test-only/feature-switch?name=feature.switch.non-js-routing&enable=false/true
> [PRM-813] - Added route checking feature switch for file upload

- app/assets/stylesheets/application.scss
- app/controllers/OtherReasonController.scala
- app/repositories/UploadJourneyRepository.scala
- app/utils/SessionKeys.scala
- app/views/components/upload/uploadList.scala.html
- app/views/reasonableExcuseJourneys/other/noJs/UploadListPage.scala.html
- app/viewtils/EvidenceFileUploadsHelper.scala
- conf/testOnlyDoNotUseInAppConf.routes
- it/controllers/OtherReasonControllerISpec.scala
- it/controllers/testOnly/FeatureSwitchControllerISpec.scala
- test/base/SpecBase.scala
- test/controllers/OtherReasonControllerSpec.scala
- test/views/UploadListPageSpec.scala
- test/viewtils/EvidenceFileUploadsHelperSpec.scala
Final implementation for non-JS journey
> [PRM-818] - Cleanup of non-js functionality + fixes

- app/controllers/predicates/AuthPredicate.scala
- app/models/UserRequest.scala
- test/controllers/AgentsControllerSpec.scala
- test/controllers/AppealAgainstObligationControllerSpec.scala
- test/controllers/AppealStartControllerSpec.scala
- test/controllers/BereavementReasonControllerSpec.scala
- test/controllers/CancelVATRegistrationControllerSpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/CrimeReasonControllerSpec.scala
- test/controllers/DuplicateAppealControllerSpec.scala
- test/controllers/FireOrFloodReasonControllerSpec.scala
- test/controllers/HealthReasonControllerSpec.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/controllers/InitialiseAppealControllerSpec.scala
- test/controllers/LossOfStaffReasonControllerSpec.scala
- test/controllers/MakingALateAppealControllerSpec.scala
- test/controllers/OtherPenaltiesForPeriodControllerSpec.scala
- test/controllers/OtherReasonControllerSpec.scala
- test/controllers/ProblemWithServiceControllerSpec.scala
- test/controllers/ReasonableExcuseControllerSpec.scala
- test/controllers/ServiceUnavailableControllerSpec.scala
- test/controllers/TechnicalIssuesReasonControllerSpec.scala
- test/controllers/UpscanControllerSpec.scala
- test/controllers/YouCannotAppealControllerSpec.scala
- test/controllers/internal/UpscanCallbackControllerSpec.scala
- test/controllers/predicates/AuthPredicateSpec.scala
- test/testUtils/AuthMocks.scala
- test/testUtils/AuthTestModels.scala
AT's currently failing locally, investigating
> [PRM-846]: removed agent data from auth retrievals

- app/views/AppealStartPage.scala.html
> [PRM-926] - Changed heading to L for 'Appeal a VAT penalty' page

- app/forms/WhyReturnSubmittedLateForm.scala
- conf/messages
- conf/messages.cy
- test/base/SpecBase.scala
- test/forms/WhyReturnSubmittedLateFormSpec.scala
- test/views/WhyReturnSubmittedLatePageSpec.scala
> PRM-927 Fix error message for LSP flow

- app/helpers/HonestyDeclarationHelper.scala
- app/views/HonestyDeclarationPage.scala.html
- build.sbt
- conf/messages
- conf/messages.cy
- test/base/SpecBase.scala
- test/helpers/HonestyDeclarationHelperSpec.scala
- test/utils/MessageRendererSpec.scala
- test/views/HonestyDeclarationPageSpec.scala
Tech issues:
Loss of staff:
Health:
Fire or flood:
Crime:
Bereavement:
> [PRM-937] - Added new agent case to honesty declaration

- app/views/AppealConfirmationPage.scala.html
https://user-images.githubusercontent.com/53828896/150093912-ceef625b-444d-4c35-9088-101105d0f8ca.mov
> [PRM-962] - Updated confirmation page for agents

- app/forms/HasHospitalStayEndedForm.scala
- app/forms/WhenDidBecomeUnableForm.scala
- app/forms/WhenDidCrimeHappenForm.scala
- app/forms/WhenDidFireOrFloodHappenForm.scala
- app/forms/WhenDidHealthIssueHappenForm.scala
- app/forms/WhenDidHospitalStayBeginForm.scala
- app/forms/WhenDidPersonLeaveTheBusinessForm.scala
- app/forms/WhenDidTechnologyIssuesBeginForm.scala
- app/forms/WhenDidTechnologyIssuesEndForm.scala
- app/forms/WhenDidThePersonDieForm.scala
- app/forms/mappings/LocalDateFormatter.scala
- app/forms/mappings/Mappings.scala
- app/views/components/inputDate.scala.html
- test/connectors/PenaltiesConnectorSpec.scala
- test/forms/HasHospitalStayEndedFormSpec.scala
- test/forms/WhenBecomeUnableFormSpec.scala
- test/forms/WhenDidCrimeHappenFormSpec.scala
- test/forms/WhenDidFireOrFloodHappenFormSpec.scala
- test/forms/WhenDidHealthIssueHappenFormSpec.scala
- test/forms/WhenDidHospitalStayBeginFormSpec.scala
- test/forms/WhenDidPersonLeaveTheBusinessFormSpec.scala
- test/forms/WhenDidTechnologyIssuesBeginFormSpec.scala
- test/forms/WhenDidTechnologyIssuesEndFormSpec.scala
- test/forms/WhenDidThePersonDieFormSpec.scala
> [PRM-1080] - Revised date input errors based on accessibility audit

- app/controllers/TimeoutController.scala
- app/views/TimeoutPage.scala.html
- app/views/layouts/Layout.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/assets/messages/TimeoutMessages.scala
- test/controllers/TimeoutControllerSpec.scala
- test/controllers/YouCannotAppealControllerSpec.scala
- test/helpers/UpscanMessageHelperSpec.scala
- test/views/TimeoutPageSpec.scala
https://user-images.githubusercontent.com/53828896/155489816-9448f201-b1e3-4140-95a5-f9664636379a.mov
https://user-images.githubusercontent.com/53828896/155489829-efca43ff-552d-412c-885a-d6f0ff76bb82.mov
> [PRM-1106] - Added timeout page

- app/assets/karma.conf.js
- app/helpers/SessionAnswersHelper.scala
- app/models/appeals/AppealSubmission.scala
- app/services/AppealService.scala
- app/views/layouts/Layout.scala.html
- build.sbt
- it/connectors/PenaltiesConnectorISpec.scala
- it/controllers/AgentsControllerISpec.scala
- it/controllers/BereavementReasonControllerISpec.scala
- it/controllers/CheckYourAnswersControllerISpec.scala
- it/controllers/CrimeReasonControllerISpec.scala
- it/controllers/FireOrFloodReasonControllerISpec.scala
- it/controllers/HealthReasonControllerISpec.scala
- it/services/AppealServiceISpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/forms/upscan/S3UploadSuccessFormSpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
- test/models/appeals/AppealSubmissionSpec.scala
- test/navigation/NavigationSpec.scala
- test/services/AppealServiceSpec.scala
Uploaded files but changed to 'no' on upload evidence question page:
```
{
"dateOfAppeal": "2022-02-24T15:11:50.906",
"appealSubmittedBy": "client",
"taxRegime": "VAT",
"sourceSystem": "MDTP",
"customerReferenceNo": "VRN224060020",
"appealInformation":
{
"honestyDeclaration": true,
"lateAppeal": true,
"statement": "x",
"reasonableExcuse": "other",
"lateAppealReason": "v",
"startDateOfEvent": "2021-01-01"
},
"isLPP": false
}
```
Uploaded files selected 'yes' on upload evidence question page:
```
{
"dateOfAppeal": "2022-02-24T15:10:07.59",
"appealSubmittedBy": "client",
"taxRegime": "VAT",
"sourceSystem": "MDTP",
"customerReferenceNo": "VRN224060020",
"appealInformation":
{
"uploadedFiles":
[
{
"reference": "a147c44a-08c1-41db-9126-21dc4bd4618f",
"fileStatus": "READY",
"downloadUrl": …
```
> [PRM-1095] - Stop uploads being sent to PEGA/SDES when the user decides not to upload files

- app/controllers/OtherPenaltiesForPeriodController.scala
- app/controllers/YouCanAppealPenaltyController.scala
- app/forms/YouCanAppealPenaltyForm.scala
- app/models/pages/Page.scala
- app/utils/SessionKeys.scala
- app/views/YouCanAppealPenaltyPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/YouCanAppealPenaltyControllerISpec.scala
- test/assets/messages/YouCanAppealThisPenaltyMessages.scala
- test/controllers/YouCanAppealPenaltyControllerSpec.scala
- test/forms/YouCanAppealPenaltyFormSpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
- test/views/YouCanAppealPenaltyPageSpec.scala
> [PRM-1117] - Added 'You can appeal this penalty' page

- app/controllers/CancelVATRegistrationController.scala
- app/controllers/YouCanAppealPenaltyController.scala
- app/navigation/Navigation.scala
- conf/application.conf
- it/controllers/CancelVATRegistrationControllerISpec.scala
- it/controllers/YouCanAppealPenaltyControllerISpec.scala
- test/base/SpecBase.scala
- test/controllers/OtherReasonControllerSpec.scala
- test/navigation/NavigationSpec.scala
~Waiting on #252 and #255~
https://user-images.githubusercontent.com/53828896/156378930-53c5c18f-ca8e-4cb6-bc0e-eb45dffe6e09.mov
> [PRM-1119] - Added routing for 'You can appeal this penalty' page

- app/assets/javascripts/upload/multiFileUpload.js
- app/assets/spec/multiFileUpload.spec.js
- app/views/partials/errorManager/message.scala.html
- app/views/reasonableExcuseJourneys/other/UploadEvidencePage.scala.html
Before:
After:
https://user-images.githubusercontent.com/53828896/156782611-0eec34f5-6e89-44c6-84b5-a27718cf2b0b.mov
> [PRM-986] - Added aria-describedby to input (using file reference) and added Error: prefix to title

- app/controllers/OtherReasonController.scala
- test/controllers/OtherReasonControllerSpec.scala
https://user-images.githubusercontent.com/86231805/157640597-b1e4b840-0e5b-4e3b-acbd-9fca77660377.mov
> [PRM-1141] Fixed incorrect routing on non-js evidence upload

- app/helpers/HonestyDeclarationHelper.scala
- app/utils/MessageRenderer.scala
- app/views/HonestyDeclarationPage.scala.html
- conf/messages
- conf/messages.cy
- test/helpers/HonestyDeclarationHelperSpec.scala
- test/utils/MessageRendererSpec.scala
- test/views/HonestyDeclarationPageSpec.scala
> [PRM-1146] - Added client missed deadline scenario for other reason

- app/forms/WhenDidHealthIssueHappenForm.scala
- app/views/reasonableExcuseJourneys/health/WhenDidHealthReasonHappenPage.scala.html
- conf/messages
- conf/messages.cy
- test/assets/messages/WhenDidBecomeUnableMessages.scala
- test/assets/messages/WhenDidHealthReasonHappenMessages.scala
- test/forms/WhenDidHealthIssueHappenFormSpec.scala
- test/views/WhenDidHealthReasonHappenPageSpec.scala
Trader / Agent planned to submit and missed deadline:
Trader LPP:
Agent LPP:
Agent planned to submit, client missed deadline:
Agent, client planned to submit:
> [PRM-1180] - Update 'when did you become unable' page for health reason

- app/controllers/OtherReasonController.scala
- app/views/reasonableExcuseJourneys/other/noJs/UploadFirstDocumentPage.scala.html
- conf/messages
- conf/messages.cy
- test/assets/messages/UploadFirstDocumentMessages.scala
- test/views/UploadFirstDocumentPageSpec.scala
> [PRM-1175] - Removed 'continue without evidence' button from non-js file upload page

- app/views/components/Header.scala.html
- conf/messages.cy
Updated the Welsh translations from line 232 to 332.
The following keys found between these lines(inclusive) in the spreadsheet are redundant:
healthReason.whenHealthIssueHappened.hintText
otherReason.uploadEvidence.uploadLabel
otherReason.uploadEvidence.noJs.button.uploadWithoutEvidence
upscan.stillUploading
The key below doesn't have the correct value hence not updated in Welsh.
otherReason.uploadList.multipleDuplicateInsetText
> [PRM-1256] Welsh translation part 2

- app/viewtils/ImplicitDateFormatter.scala
- conf/messages
- conf/messages.cy
- test/base/SpecBase.scala
- test/viewtils/ImplicitDateFormatterSpec.scala
Screenshot shows translated date, other content is yet to be translated:
> [PRM-1267] - Added Welsh dates

- app/forms/mappings/LocalDateFormatter.scala
- app/views/components/inputDate.scala.html
- conf/messages.cy
Title update (on error):
Date update (mis = month):
> [PRM-1272] - Added day/month/year Welsh wording to error message

- app/controllers/AppealStartController.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/HonestyDeclarationController.scala
- app/controllers/InitialiseAppealController.scala
- app/helpers/DateTimeHelper.scala
- app/models/v2/AppealData.scala
- app/navigation/Navigation.scala
- app/services/AppealService.scala
- app/views/components/characterCount.scala.html
- app/views/components/inputDate.scala.html
- app/views/components/pageHeader.scala.html
- app/views/components/radios.scala.html
- app/views/layouts/GovUkPageLayout.scala.html
- app/viewtils/ConditionalRadioHelper.scala
- app/viewtils/PenaltyTypeHelper.scala
- test/controllers/InitialiseAppealControllerSpec.scala
- test/models/v2/AppealDataSpec.scala
- test/services/AppealServiceSpec.scala
- test/viewtils/PenaltyTypeHelperSpec.scala
Tested locally with some reasonable excuses + obligation, appeal submitted successfully.
> [PRM-1310] - Updated appeals handling for new API

- app/views/components/upload/uploadList.scala.html
- test/base/SpecBase.scala
https://user-images.githubusercontent.com/53828896/168763325-b5556fd8-354c-41d5-89c9-489ed0c8be89.mov
> [PRM-1340] - Added routing for removal of files on non-js upload page

- app/config/AppConfig.scala
- app/config/featureSwitches/FeatureSwitch.scala
- app/config/featureSwitches/FeatureSwitching.scala
- app/controllers/AppealStartController.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/HonestyDeclarationController.scala
- app/controllers/OtherReasonController.scala
- app/controllers/RemoveFileController.scala
- app/controllers/testOnly/FeatureSwitchController.scala
- app/helpers/UpscanMessageHelper.scala
- app/navigation/Navigation.scala
- app/services/AppealService.scala
- app/viewtils/PenaltyTypeHelper.scala
- conf/application.conf
- conf/testOnlyDoNotUseInAppConf.routes
- it/controllers/OtherReasonControllerISpec.scala
- test/base/SpecBase.scala
- test/config/featureSwitches/FeatureSwitchingSpec.scala
- test/controllers/AppealStartControllerSpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/HonestyDeclarationControllerSpec.scala
- test/controllers/OtherReasonControllerSpec.scala
- test/controllers/testOnly/FeatureSwitchControllerSpec.scala
- test/navigation/NavigationSpec.scala
Use either CURL or config value to set feature switch
> [PRM-1365] - Revised feature switch implementation

- app/views/components/radios.scala.html
> [PRM-1401] Reduced margins

- app/controllers/CheckYourAnswersController.scala
- test/base/SpecBase.scala
- test/views/AppealConfirmationPageSpec.scala
> [PRM-1428-B] Removed 'Additional' in appeal journey confirmation page

- app/assets/javascripts/upload/multiFileUpload.js
- app/assets/spec/multiFileUpload.spec.js
Also allows users to continue where there is errors on the page (because the page is optional)
Needs ATs
> [PRM-1520] - Hidden remove link for empty rows and file that have errored

- app/controllers/UpscanController.scala
- app/helpers/UpscanMessageHelper.scala
- app/repositories/UploadJourneyRepository.scala
- conf/messages
- conf/messages.cy
- it/controllers/UpscanControllerISpec.scala
- it/repositories/UploadJourneyRepositoryISpec.scala
- test/controllers/UpscanControllerSpec.scala
- test/helpers/UpscanMessageHelperSpec.scala
> PRM-1522 JS journey, updated error message content

- app/controllers/PenaltySelectionController.scala
- app/models/pages/Page.scala
- app/navigation/Navigation.scala
- app/views/AppealSinglePenaltyPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/PenaltySelectionControllerISpec.scala
- test/assets/messages/AppealSinglePenaltyMessages.scala
- test/controllers/PenaltySelectionControllerSpec.scala
- test/navigation/NavigationSpec.scala
- test/views/AppealSinglePenaltyPageSpec.scala
> [PRM-1578] - Added appealing a single penalty page

- app/helpers/SessionAnswersHelper.scala
- it/controllers/CheckYourAnswersControllerISpec.scala
- test/helpers/SessionAnswersHelperSpec.scala
> [PRM-1581] - Added CYA row for appealing both penalties

- conf/messages
- test/assets/messages/AppealStartMessages.scala
> [PRM-1634] - Changed content on appeal start page

- app/navigation/Navigation.scala
- it/controllers/PenaltySelectionControllerISpec.scala
- test/navigation/NavigationSpec.scala
https://user-images.githubusercontent.com/53828896/185349222-92ac550c-da09-4d59-a9f4-1e4d88583d42.mov
> [PRM-1681] - Route to making a late appeal page when appealing both penalties

- conf/messages
- it/controllers/UpscanControllerISpec.scala
- it/controllers/internal/UpscanCallbackControllerISpec.scala
- test/assets/messages/UploadEvidenceMessages.scala
- test/helpers/UpscanMessageHelperSpec.scala
Phantom unit tests failing, but passes against AT's and PT's pass.
> [PRM-1674]: updated upload error messages

- app/helpers/AppealConfirmationHelper.scala
- app/views/AppealConfirmationPage.scala.html
- conf/messages
- conf/messages.cy
- test/assets/messages/AppealConfirmationMessages.scala
- test/base/SpecBase.scala
- test/helpers/AppealConfirmationHelperTest.scala
- test/views/AppealConfirmationPageSpec.scala
> PRM-1677 Updated Content on confirmation page

- app/controllers/CheckYourAnswersController.scala
- app/controllers/IncompleteSessionDataController.scala
- app/views/errors/IncompleteSessionDataPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- it/controllers/CheckYourAnswersControllerISpec.scala
- test/assets/messages/IncompleteSessionDataMessages.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/IncompleteSessionDataControllerSpec.scala
- test/views/IncompleteSessionDataPageSpec.scala
> [PRM-1725] - Added page when session data is incomplete

- conf/messages.cy
Lines 5 to 60 in the spreadsheet [https://docs.google.com/spreadsheets/d/1BWF-feicBcc73q8uOSGVHymQSZRl2SnH/edit#gid=1456740952](url)
> [PRM-1785] Welsh translation part 2

- app/controllers/UpscanController.scala
- app/controllers/internal/UpscanCallbackController.scala
- app/helpers/UpscanMessageHelper.scala
- it/controllers/UpscanControllerISpec.scala
- it/controllers/internal/UpscanCallbackControllerISpec.scala
- test/controllers/UpscanControllerSpec.scala
- test/helpers/UpscanMessageHelperSpec.scala
> [PRM-1826] - Fixed JS upload error messages not translating

- app/views/HonestyDeclarationPage.scala.html
- test/views/HonestyDeclarationPageSpec.scala
> [PRM-1998] - Updated content for client missing deadline and loss of staff reason selected

- app/assets/spec/multiFileUpload.spec.js
- app/views/layouts/GovUkPageLayout.scala.html
> [PRM-2133] - Passed lang parameter to GOVUK layout and fixed Node.JS warnings

- conf/application.conf
- test/views/AppealStartPageSpec.scala
> [PRM-2166] - Added accessibility statement service path

- app/config/AppConfig.scala
- app/views/ReasonableExcuseSelectionPage.scala.html
- conf/application.conf
- test/views/ReasonableExcuseSelectionPageSpec.scala
https://user-images.githubusercontent.com/53828896/212650011-624edeb1-9a45-4ebd-ab58-30986026f5dc.mov
> [PRM-2183] - Added reasonable excuse guidance link

- app/views/components/inputDate.scala.html
- app/views/reasonableExcuseJourneys/bereavement/WhenDidThePersonDiePage.scala.html
- app/views/reasonableExcuseJourneys/crime/WhenDidCrimeHappenPage.scala.html
- app/views/reasonableExcuseJourneys/fireOrFlood/WhenDidFireOrFloodHappenPage.scala.html
- app/views/reasonableExcuseJourneys/health/WhenDidHealthReasonHappenPage.scala.html
- app/views/reasonableExcuseJourneys/health/WhenDidHospitalStayBeginPage.scala.html
- app/views/reasonableExcuseJourneys/lossOfStaff/WhenDidThePersonLeaveBusinessPage.scala.html
- app/views/reasonableExcuseJourneys/other/WhenDidBecomeUnablePage.scala.html
- app/views/reasonableExcuseJourneys/technicalIssues/TechnologyIssuesDatePage.scala.html
- scalastyle-config.xml
> [PRM-2212] - Changed styling of date input pages

- app/config/AppConfig.scala
- app/connectors/PenaltiesConnector.scala
- app/services/AppealService.scala
- it/connectors/PenaltiesConnectorISpec.scala
- it/services/AppealServiceISpec.scala
- it/stubs/PenaltiesStub.scala
- project/plugins.sbt
- test/connectors/PenaltiesConnectorSpec.scala
- test/services/AppealServiceSpec.scala
Renders confirmation page even if part of multi appeal fails
> [PRM-2192] - Add handling for partial failure of multi-appeal journey

- conf/messages.cy
13 CThEM were changed to CThEF
> [PRM-2252] Changed CThEM to CThEF for the Welsh messages

- app/config/featureSwitches/FeatureSwitch.scala
- app/controllers/CheckYourAnswersController.scala
- app/views/AppealConfirmationPage.scala.html
- conf/application.conf
- test/config/featureSwitches/FeatureSwitchingSpec.scala
- test/views/AppealConfirmationPageSpec.scala
> [PRM-2317] Added Digital Comms Message as a feature switch and used it on the confirmation page 

- app/navigation/Navigation.scala
- test/navigation/NavigationSpec.scala
> [PRM-2306] - Added routing for appeal by letter page

- app/assets/javascripts/upload/multiFileUpload.js
- app/assets/spec/multiFileUpload.spec.js
- app/views/components/upload/uploadItem.scala.html
- app/views/reasonableExcuseJourneys/other/UploadEvidencePage.scala.html
- conf/messages
- conf/messages.cy
> [PRM-2319] - Added more screen reader notifications to (JS) file upload page

- app/controllers/OtherReasonController.scala
- app/views/reasonableExcuseJourneys/other/UploadEvidencePage.scala.html
- test/assets/messages/UploadEvidenceMessages.scala
- test/views/UploadEvidencePageSpec.scala
> [PRM-2359] Added skip file button to js upload page

- app/config/featureSwitches/FeatureSwitch.scala
- app/controllers/HealthReasonController.scala
- app/forms/HasHospitalStayEndedNonConditionalForm.scala
- app/viewtils/RadioOptionHelper.scala
- conf/application.conf
- it/controllers/HealthReasonControllerISpec.scala
- test/config/featureSwitches/FeatureSwitchingSpec.scala
- test/controllers/HealthReasonControllerSpec.scala
- test/forms/HasHospitalStayEndedNonConditionalFormSpec.scala
> [PRM-2368] - Feature switch 'has hospital stay ended' page until new variation ready

- app/helpers/SessionAnswersHelper.scala
- app/navigation/Navigation.scala
- test/helpers/SessionAnswersHelperSpec.scala
- test/navigation/NavigationSpec.scala
> [PRM-2367] - Navigation for hospital stay end date

- app/controllers/HealthReasonController.scala
- conf/application.conf
- it/controllers/HealthReasonControllerISpec.scala
- test/controllers/HealthReasonControllerSpec.scala
App config prod change, to prevent this being shown in prod until its been signed off: https://github.com/hmrc/app-config-production/pull/17720
Passes against https://github.com/hmrc/penalties-acceptance-tests/pull/247
Waiting on #435
> [PRM-2415] - Turn on hospital stay end page feature switch

- conf/messages.cy
> [PRM-2420] - Implemented remaining Welsh for 'When did hospital stay end' page

- app/viewtils/ImplicitDateFormatter.scala
- conf/messages
- conf/messages.cy
- test/assets/messages/HasTheHospitalStayEndedMessages.scala
- test/assets/messages/WhenDidBecomeUnableMessages.scala
- test/assets/messages/WhenDidCrimeHappenMessages.scala
- test/assets/messages/WhenDidFireOrFloodHappenMessages.scala
- test/assets/messages/WhenDidHealthReasonHappenMessages.scala
- test/assets/messages/WhenDidHospitalStayBeginMessages.scala
- test/assets/messages/WhenDidHospitalStayEndMessages.scala
- test/assets/messages/WhenDidTechnologyIssuesBeginMessages.scala
- test/assets/messages/WhenDidTechnologyIssuesEndMessages.scala
- test/assets/messages/WhenDidThePersonDiePageMessages.scala
- test/assets/messages/WhenDidThePersonLeaveBusinessMessages.scala
- test/helpers/SessionAnswersHelperSpec.scala
- test/viewtils/ImplicitDateFormatterSpec.scala
> PRM-2401 Added nbsp to dates

- app/forms/WhenDidHospitalStayEndForm.scala
- conf/messages
- conf/messages.cy
- test/forms/WhenDidHospitalStayEndFormSpec.scala
> [PRM-2460] - Adjusted error message for hospital stay end date page

- app/forms/MakingALateAppealForm.scala
- app/forms/OtherRelevantInformationForm.scala
- app/forms/WhyReturnSubmittedLateForm.scala
- app/utils/RegexHelper.scala
- conf/messages
- conf/messages.cy
- it/controllers/AppealAgainstObligationControllerISpec.scala
- it/controllers/MakingALateAppealControllerISpec.scala
- it/controllers/OtherReasonControllerISpec.scala
- test/base/SpecBase.scala
- test/controllers/AppealAgainstObligationControllerSpec.scala
- test/controllers/MakingALateAppealControllerSpec.scala
- test/controllers/OtherReasonControllerSpec.scala
- test/forms/MakingALateAppealFormSpec.scala
- test/forms/OtherRelevantInformationFormSpec.scala
- test/forms/WhyReturnSubmittedLateFormSpec.scala
- test/utils/RegexHelperSpec.scala
https://user-images.githubusercontent.com/6122384/229803035-fcb9dd99-7ee2-4d11-be5e-4e01da5e1c13.mov
> PRM-2462 Added validation to text areas

- app/controllers/YouCannotGoBackToAppealController.scala
- app/models/pages/Page.scala
- app/views/errors/DuplicateAppealPage.scala.html
- app/views/errors/ServiceUnavailablePage.scala.html
- app/views/errors/YouCannotGoBackToAppealPage.scala.html
- conf/app.routes
- conf/messages
- conf/messages.cy
- test/assets/messages/YouCannotGoBackToAppealMessages.scala
- test/controllers/YouCannotGoBackToAppealControllerSpec.scala
- test/views/YouCannotGoBackToAppealPageSpec.scala
Trader - English:
Trader - Welsh:
Agent - English:
Agent - Welsh:
> [PRM-2477] - Added you cannot go back to appeal details page

- conf/messages
- conf/messages.cy
- test/assets/messages/YouCannotGoBackToAppealMessages.scala
> [PRM-2498] - Remove 'Let us know' from you cannot go back to appeal details page

- app/views/CheckYourAnswersPage.scala.html
- app/views/components/warningText.scala.html
- conf/messages
- conf/messages.cy
- test/assets/messages/CheckYourAnswersMessages.scala
- test/views/CheckYourAnswersPageSpec.scala
> [PRM-2528] - Changed CYA declaration to warning text

- app/assets/javascripts/upload/multiFileUpload.js
- app/assets/spec/multiFileUpload.spec.js
> [PRM-2524] - Set heading to h2 for successfully uploaded files

- app/views/components/inputDate.scala.html
- app/views/reasonableExcuseJourneys/lossOfStaff/WhenDidThePersonLeaveBusinessPage.scala.html
- conf/messages
- conf/messages.cy
- test/assets/messages/WhenDidThePersonLeaveBusinessMessages.scala
- test/views/WhenDidThePersonLeaveBusinessPageSpec.scala
> [PRM-2530] - Adjust formatting of loss of staff date page

- app/forms/mappings/LocalDateFormatter.scala
- app/views/components/inputDate.scala.html
- test/views/components/InputDateSpec.scala
Similar to #459 however added a check for Welsh rather than over-engineering it
> [PRM-2526] - Fixed highlighting issue where 2 or more fields have errors

- app/config/featureSwitches/FeatureSwitch.scala
- app/controllers/InitialiseAppealController.scala
- app/models/monitoring/PenaltyAppealStartedAuditModel.scala
- app/services/monitoring/JsonAuditModel.scala
- conf/application.conf
- test/config/featureSwitches/FeatureSwitchingSpec.scala
- test/controllers/InitialiseAppealControllerSpec.scala
- test/models/monitoring/PenaltyAppealStartedAuditModelSpec.scala
Waiting on #469 
See Git channel for evidence
> [PRM-2556] - Added audit event for appeal start

- app/forms/mappings/LocalDateFormatter.scala
- test/views/components/InputDateSpec.scala
> [PRM-2526] - Link to day field when all fields highlighted & adjust highlighting for leap year when there is other errors

- app/config/featureSwitches/FeatureSwitch.scala
- app/connectors/PenaltiesConnector.scala
- app/connectors/httpParsers/AppealSubmissionHTTPParser.scala
- app/connectors/httpParsers/ErrorResponse.scala
- app/controllers/InitialiseAppealController.scala
- app/models/appeals/AppealSubmissionResponseModel.scala
- app/models/monitoring/AppealAuditModel.scala
- app/services/AppealService.scala
- conf/application.conf
- it/connectors/PenaltiesConnectorISpec.scala
- it/services/AppealServiceISpec.scala
- it/stubs/PenaltiesStub.scala
- test/config/featureSwitches/FeatureSwitchingSpec.scala
- test/connectors/PenaltiesConnectorSpec.scala
- test/connectors/httpParsers/AppealSubmissionParserSpec.scala
- test/controllers/InitialiseAppealControllerSpec.scala
- test/models/appeals/AppealSubmissionResponseModelSpec.scala
- test/models/monitoring/AppealAuditModelSpec.scala
- test/services/AppealServiceSpec.scala
App conf prod PR: https://github.com/hmrc/app-config-production/pull/18290
> [PRM-2558] - Add new feature switch for case ID in audit and modified appeal logic and handling

- app/controllers/CheckYourAnswersController.scala
- app/controllers/InitialiseAppealController.scala
- app/controllers/predicates/DataRequiredAction.scala
- app/controllers/predicates/DataRetrievalAction.scala
- app/repositories/UserAnswersRepository.scala
- app/utils/SessionKeys.scala
- it/controllers/CheckYourAnswersControllerISpec.scala
- it/repositories/UserAnswersRepositoryISpec.scala
- test/base/UserAnswersBase.scala
- test/controllers/predicates/DataRequiredActionSpec.scala
- test/controllers/predicates/DataRetrievalActionSpec.scala
Reverts hmrc/penalties-appeals-frontend#499
Needs further thinking
> Revert "[PRM-2851] - Kept data in session post-appeal"

- app/config/AppConfig.scala
- conf/application.conf
- it/utils/IntegrationSpecCommonBase.scala
https://github.com/hmrc/app-config-base/pull/9397
https://github.com/hmrc/app-config-staging/pull/13847
> [PRM-2949] - Use relative and absolute redirects

- app/config/ErrorHandler.scala
- app/controllers/TechnicalErrorController.scala
- app/views/errors/ErrorTemplate.scala.html
- app/views/errors/TechnicalErrorPage.scala.html
- conf/app.routes
- conf/application.conf
- test/config/ErrorHandlerSpec.scala
- test/controllers/TechnicalErrorControllerSpec.scala
- test/views/errors/TechnicalErrorPageSpec.scala
> [PRM-2943] Created new page for 403 error

- conf/messages
- conf/messages.cy
- test/assets/messages/findOutHowToAppeal/HowToAppealMessages.scala
> PRM-3109 Added missing write to content

- app/config/AppConfig.scala
- app/controllers/findOutHowToAppeal/ActionsToTakeBeforeAppealingOnlineController.scala
- app/models/pages/Page.scala
- app/navigation/Navigation.scala
- app/views/components/link.scala.html
- app/views/findOutHowToAppeal/ActionsToTakeBeforeAppealingOnlinePage.scala.html
- app/views/layouts/PageLayout.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages
- conf/messages.cy
- it/controllers/findOutHowToAppeal/ActionsToTakeBeforeAppealingOnlineControllerISpec.scala
- test/assets/messages/findOutHowToAppeal/ActionsToTakeBeforeAppealingOnlineMessages.scala
- test/base/BaseSelectors.scala
- test/controllers/findOutHowToAppeal/ActionsToTakeBeforeAppealingOnlineControllerSpec.scala
- test/navigation/NavigationSpec.scala
- test/views/findOutHowToAppeal/ActionsToTakeBeforeAppealingOnlinePageSpec.scala
'No' flow for LSP 'find out how to appeal' journey
> [PRM-3135] - Added actions to take before appealing online page
